server:
  port: 8082

spring:
  application:
    name: cuenta-service

  datasource:
    url: jdbc:postgresql://devsu-postgres:5432/devsu
    username: devsu
    password: devsu

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: devsu-rabbitmq
    port: 5672
    username: guest
    password: guest
    
cliente:
  service:
    base-url: http://cliente-service:8081